qna/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path("users/", include("qna.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("users/", include('qna.users.urls'), name="users"),
    path("", include('qna.curation.urls'), name="curation"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

qna/qna/curation/urls.py
from django.urls import path
from. import views 


app_name = "curation"
urlpatterns = [
    # /curation/
    path("", views.main, name="main"),
    path("neck/", views.neck, name="neck"),
    path("shoulder/", views.shoulder, name="shoulder"),
    path("back/", views.back, name="back"),
    path("hip/", views.hip, name="hip"),
    path("knee/", views.knee, name="knee"),
    path("qna/<str:q_name>/<int:q_id>/", views.getQna, name="getQna"),
    path("result/", views.result, name="result"),
    path("manage/", views.manage, name="manage"),
    path("<int:q_id>/list/", views.list, name="list"),
    path("<int:q_id>/edit/", views.edit, name="edit"),

    path("qnaResister/", views.register, name="register"),

]

qna/qna/users/urls.py
from django.urls import path
from . import views

from qna.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.register, name="register"),


    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),

]
    # path("", views.main, name="main"),
    # path("neck/", views.neck, name="neck"),
    # path("shoulder/", views.shoulder, name="sh

qna/qna/curation/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Answer, Question

class EditQnaForm(forms.ModelForm):
    question_text = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))
    class Meta:
        model = Question
        fields=['question_text']
        labels = {}



class QnaForm(forms.ModelForm):
    class Meta:
        model = Question
        fields=['question_category', 'question_title', 'question_text']
        labels = {}

    
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields=['answer_text', 'value', 'category']
        labels = {}

    

    # def save(self, commit=True):
    #     question = super().save(commit=commit)
    #     if commit:
    #         for answer_form in self.answer_forms:
    #             answer = answer_form.save(commit=False)
    #             answer.question = question
    #             answer.save()
    #         self.answer_forms.is_valid()  # Call is_valid() on the formset to trigger the clean() method
    #         self.answer_forms.save()
    #     return question

qna/qna/curation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q
from django.forms import formset_factory
from django.core.cache import cache
from . import models, serializers, forms
import json, copy


selected=[]
answer=[]
first, endPont=5, 11

def edit(request, q_id):
    if request.user.is_authenticated:
        question=models.Question.objects.get(id=q_id)
        AnswerFormSet = formset_factory(forms.AnswerForm, extra=0)
        
        if request.user != question.author :
            return redirect(reverse('curation:main'))

        if request.method == 'GET':
            form=forms.EditQnaForm(instance=question)
            answers = models.Answer.objects.filter(question=question).order_by('id')

            initial_data = []
            for answer in answers:
                initial_data.append({
                    'answer_text': answer.answer_text,
                    'value': answer.value,
                    'category': answer.category
                })

            formset = AnswerFormSet(initial=initial_data)
            return render(request, 'curation/edit.html', {'form': form, 'formset': formset, 'question':question})
        
        elif request.method == 'POST':
            
            form=forms.EditQnaForm(request.POST)
            formset=AnswerFormSet(request.POST)
            answers = models.Answer.objects.filter(question=question).order_by('id')

            if form.is_valid() and formset.is_valid():
                question.question_text=form.cleaned_data['question_text']
                question.save()

                for i in range(len(answers)):
                    answer=answers[i]
                    answer.answer_text=formset[i].cleaned_data['answer_text']
                    answer.value=formset[i].cleaned_data['value']
                    answer.category=formset[i].cleaned_data['category']
                    answer.save()
            
                return redirect(reverse('curation:manage'))

            else:
                print('not valid form')
                
    return render(request, 'curation/list.html')

def list(request, q_id):
    if request.user.is_authenticated:
        ## if request.user == author 일치하면
        q = models.Question.objects.get(id=q_id)
        q_s=serializer = serializers.QnaSerializer(q)

        questions = models.Question.objects.filter(id__range=(q_id, q_id + 6)).order_by("id")
       
        question_data = []
        for question in questions:
            serializer = serializers.QnaSerializer(question)
            question_data.append({
                'question': serializer.data,
                'answers': question.answer_q.all()[:3]  # 역참조
            })

        return render(request, 'curation/list.html', {'q_s':q_s, 'question_data': question_data})


        if request.method == 'GET':
            form=forms.QnaForm(instance=questions)
            return render(request, 'curation/list.html', {"form":form, "questions":questions})


def manage(request):
    if request.user.is_authenticated:
        if not request.user.user_type.userType == 'customer':
            questions = models.Question.objects.all().order_by("create")
            serializer = serializers.QnaSerializer(questions, many=True)
            return render(request, 'curation/manage.html', {'data':serializer.data})
          

cnt = 0
qList=[]
aList=[]                                                                                          
def register(request):   
    global cnt,qList,aList
    AnswerFormSet = formset_factory(forms.AnswerForm, extra=3)

    if request.method == 'GET':
        cnt=0
        qList=[]
        aList=[] 
        form = forms.QnaForm()
        formset = AnswerFormSet()
        return render(request, 'curation/register.html', {'form': form, 'formset': formset})
    
    elif request.method == 'POST':
        form = forms.QnaForm(request.POST)
        formset = AnswerFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            # print(request.POST['q_index'])
            parent = form.save(commit=False)
            qList.append(parent)
            # parent.save()
            

            for form2 in formset:
                child = form2.save(commit=False)
                child.question = parent
                aList.append(child)
                # child.save()
            cnt+=1
            print(cnt)

            # 이전 입력값 지워주기
            form = forms.QnaForm(initial={'question_category': form.cleaned_data['question_category'],
                                          'question_title':form.cleaned_data['question_title']})
            # formset = AnswerFormSet()

            # form.save()한 뒤에 form.cleaned_data['칼럼명']을 reverse()로 전달하여 질문 카테고리에 따라 동적으로 redirect 페이지를 변경
            question_category=form.cleaned_data['question_category']

            if cnt == 2 :
                for q in qList:
                    q.save()

                for a in aList:
                    a.save()

                url = reverse(f'curation:{question_category}')
                cnt=0 # 질문 갯수를 채우면, 다시 카운트를 0으로 돌려줘야
                return HttpResponseRedirect(url)
                        
            return render(request, 'curation/register.html', {'form': form, 'formset': formset})
        
        else:
            print('not valid form')
            return render(request, 'curation/register.html', {'form': form, 'formset': formset})



def main(request):
    return render(request, 'curation/main.html')

def neck(request):
    question=models.Question.objects.filter(question_category__name__iexact='neck').first()
    serializer = serializers.QnaSerializer(question)
    return render(request, 'curation/neck.html', {'data':serializer.data})

def shoulder(request):
    question=models.Question.objects.filter(question_category__name__iexact='shoulder').first()
    serializer = serializers.QnaSerializer(question)
    return render(request, 'curation/shoulder.html', {'data':serializer.data})

def back(request):
    question=models.Question.objects.filter(question_category__name__iexact='back').first()
    serializer = serializers.QnaSerializer(question)
    return render(request, 'curation/back.html', {'data':serializer.data})


def hip(request):
    question=models.Question.objects.filter(question_category__name__iexact='hip').first()
    serializer = serializers.QnaSerializer(question)
    return render(request, 'curation/hip.html', {'data':serializer.data})


def knee(request):
    question=models.Question.objects.filter(question_category__name__iexact='knee').first()
    serializer = serializers.QnaSerializer(question)
    return render(request, 'curation/knee.html', {'data':serializer.data})

def getQna(request, q_name, q_id):
    if request.method == 'GET':

        # question=get_object_or_404(models.Question, pk=1)
        # question=models.Question.objects.get(id=q_id)
        # serializer = serializers.QnaSerializer(question)
        # return render(request, 'curation/qna.html', {"question":serializer.data})
        if q_id % 7 == 5:
            if 'first' not in request.session: 
                request.session['first'] = 'first'
                question = models.Question.objects.get(question_category__name__iexact=q_name, id=q_id)
                serializer = serializers.QnaSerializer(question)
                return render(request, 'curation/qna.html', {"question":serializer.data})
            else :
                del request.session['first']
                question = models.Question.objects.get(question_category__name__iexact=q_name, id=q_id+1)
                serializer = serializers.QnaSerializer(question)
                return render(request, 'curation/qna.html', {"question":serializer.data})
            
        elif q_id % 7 == 4:
            if 'first' in request.session: 
                del request.session['first']
            return redirect(reverse('curation:result'))
        
        else :
            if 'first' in request.session: 
                del request.session['first']
            question = models.Question.objects.get(question_category__name__iexact=q_name, id=q_id+1)
            serializer = serializers.QnaSerializer(question)
            return render(request, 'curation/qna.html', {"question":serializer.data})


    elif request.method == 'POST':
        response_body = {"q": "", "a": [], "q_id":""}
        # question=models.Question.objects.get(id=q_id+1)
        # response_body['q'] = question.question_text
        # response_body['q_id'] = question.id

        # answers = question.answer_q.all()
        # for answer in answers:
        #     response_body['a'].append({
        #     'id': answer.id,
        #     'text': answer.answer_text,
        #     'category': answer.category.name,
        #     'value':answer.value,
        # })
        data = json.loads(request.body.decode('utf-8'))
        selected.append(data)
        return JsonResponse(status=200, data=response_body)
    


def result(request):
    # 최고값인 category를 전달 받아 resultSerializer로 html에 전달해주기
    point={}
    global selected
    print(selected)
    answer=copy.deepcopy(selected)
    selected=[]

    for a_id in answer:
        a=models.Answer.objects.get(id=a_id)
        if a.category in point :
            point[a.category]+=a.value
        else :
            point[a.category]=a.value

    point=sorted(point.items(), key=lambda x: x[1])
    pointer=point[-1][0]
    print(pointer)
    answer_result=models.Result.objects.get(category=pointer)
    serializer = serializers.ResultSerializer(answer_result)
    
    return render(request, 'curation/result.html', {'result':serializer.data})

qna/qna/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.http import HttpResponse

from django.urls import reverse
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login
from . import forms, models

User = get_user_model()




def register(request):
    if request.method == 'GET':
        form = forms.RegistrationForm()
        return render(request, 'users/register.html', {'form': form})
    
    elif request.method == 'POST':
        form = forms.RegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            print(username, password)
            
            # 가입후 자동 로그인
            user=authenticate(request, username=username, password=password)
            if user is not None :
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                print('로그인')
                return redirect(reverse('curation:main'))
            else :
                print('로그인 실패')
                return redirect(reverse('users:register'))

        return HttpResponse(status=405)
        


def user_login(request):
    if request.method=='GET':
        return render(request, 'users/login.html')
    
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        
        user=authenticate(request, username=username, password=password)
        user = User.objects.get(username=username)
        user_type = user.user_type.userType
        print(user_type)
        
        if user is not None :
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            print('로그인')
            return HttpResponseRedirect(reverse('curation:main'))
        else :
            print('로그인 실패')
            return HttpResponseRedirect(reverse('curation:main'))
        
def user_logout(request):
    logout(request)
    # Perform any additional actions after logout if needed
    # For example, you can redirect the user to a specific page or display a success message
    return redirect(reverse('curation:main'))         

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

qna/qna/templates/curation/back.html
{%extends 'curation/base.html'%}
{% load static%}

{%block content%}
<div class="col-lg-6 col-md-8 col-sm-10 col-12 mx-auto">

    <img src="{%static 'images/curation/lumbar.jpg'%}" alt="backpain" class="img-fluid">
    </div>

  <p class="titlecontent mt-2">허리가 아플때<br>어떤 운동을 하면 좋을까?</p>

  
  
  <button type="button" class="back btn-outline-danger btn-lg" onclick = 'location.href = "{% url 'curation:getQna' data.question_category.name data.id %}"' >시작하기</button>
  
  {% comment %} onclick="js:begin()" {% endcomment %}
{%endblock content%}

qna/qna/templates/curation/base.html
{% load static%}
<!DOCTYPE html>
<html lang="ko" dir="ltr">

<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Play_With">
    <meta name="keywords" content="curation for workout">
    <meta name="description" content="curation for workout">

    <!-- sns share -->
    <!-- <meta property="og:url" content="https://neckpainworkout.netlify.app" />
    <meta property="og:title" content="필라텥스 강사가 추천하는 허리 통증 운동" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="lumbar1.jpg" />
    <meta property="og:description" content="허리가 아플 때 하면 좋은 운동" /> -->


    <!-- <link rel="shortcut icon" href="favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="favicon.ico" /> -->

    <title>증상별 운동</title>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&family=Nanum+Pen+Script&display=swap" rel="stylesheet">

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- <link rel="stylesheet" href="./css/basic.css">
    <link rel="stylesheet" href="./css/main.css">
    <link rel="stylesheet" href="./css/qna.css">
    <link rel="stylesheet" href="./css/animation.css">
    <link rel="stylesheet" href="./css/result.css"> -->
    <link rel="stylesheet" href="{% static 'css/curation/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/curation/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/curation/result.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/curation/qna.css' %}"> {% endcomment %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  <meta name="naver-site-verification" content="2dc4a0d1eb29e08a9292f0cfab05dc5d42609840" />
  <link rel="canonical" href="https://backpainworkout.netlify.app">
  
  <meta name="google-site-verification" content="OqyB5GPV7c1TuCKrhBCLCk0NeGxeh483y1mm99dRjYM" />
  
</head>

<body>



<div class="container">

 
  <nav class="navbar navbar-expand-lg mx-auto navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand">Play_With</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%url 'curation:neck'%}">목</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'curation:shoulder'%}">어깨</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'curation:back' %}">허리</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'curation:hip'%}">고관절</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{%url 'curation:knee'%}">무릎</a>
      </li>
    </ul>
    </div>
  </div>
</nav>

  <div class="users">
    {% if not request.user.is_authenticated %}
        <a class="user_link" href="{%url 'users:login'%}">로그인</a>
        
        <a class="user_link" href="{% url 'users:register' %}">회원가입</a>
        
      {% elif request.user.is_authenticated %}
    
        <a class="user_link" href="{%url 'users:logout'%}">로그아웃</a>
        
        {% if not request.user.user_type.userType == 'customer' %}
        
            <a class="user_link" href="{%url 'curation:register'%}">QnA 등록</a>
            
            <a class="user_link" href="{%url 'curation:manage'%}">QnA 관리</a>
           
        {%endif%}
      {%endif%}

  </div>
  


<section id="main" class="mx-auto pb-3 pt-3">
  {% comment %} <h2>필라테스 강사가 추천하는 <br> 통증별 운동프로그램</h2> {% endcomment %}


{%block content %}

{% endblock %}

<!-- </section>

{% comment %} <section id="qna">
  <div class="status mx-auto mt-5">
        <div class="statusBar">
        </div>
  </div>

      <div class="qBox my-5 py-1 mx-auto">
      </div>

      <div class="answerBox">
      </div>
</section> {% endcomment %}


  {% comment %} <section id="result" class="my-5 py-3 mx-auto">
        <div class="resultName"></div>

        <div class="resultDesc"></div>

        <div class="youtube" class="my-5 col-lg-6 col-md-8 col-sm-10 col- mx-auto">
        </div>

            <div style = "text-align:center; margin-top:2px;"> <div style="font-size:10px;"> <span class="ad">광고 / 제휴 / 개인PT 문의 : weplaylegowithyou@gmail.com</span> </div> <div style="margin-top:1rem;"> <h6 style="font-family: 'Lobster', cursive;"></h6> </div> </div>

<div id="disqus_thread" style = "margin-bottom:5px;"></div>
</section> -->

</div> 


<script>
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://backpainworkout.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>


    {% comment %} <script src="{%static 'js/qna.js'%}" charset="utf-8"></script>  {% endcomment %}
</body>
</html>

qna/qna/templates/curation/edit.html
{%extends 'curation/base.html'%}
{% load static%}

{%block content%}
<style>
    .form{
        font-size: 26px;
    }
    .answer_table {
        margin: 0 auto;
        
    }
</style>


<form action="{% url 'curation:edit' question.id %}" method="post">
    {%csrf_token%}
    <div class="form">
        <br>
        {{form.question_text}}
        <br><br>
        
        <table class="answer_table">
            <tr>
                <th>답안</th>
                <th>가중치</th>
                <th>카테고리</th>
            </tr>
            
            {% for form in formset %}
            {{formset.management_form}}
            <tr>
                <td>{{ form.answer_text }}</td>
                <td>{{ form.value }}</td>
                <td>{{ form.category }}</td>
            </tr>
            {% endfor %}
        </table>
        <br><br><br>
        <input type="submit" value="수정">
    </div>
</form>
{%endblock content%}

qna/qna/templates/curation/hip.html
{%extends 'curation/base.html'%}
{% load static%}

{%block content%}
<div class="col-lg-6 col-md-8 col-sm-10 col-12 mx-auto">
    <img src="{%static 'images/curation/hip.jpg'%}" alt="hippain" class="img-fluid">
    </div>
  <h2>필라테스 강사가 추천하는 <br> 통증별 운동프로그램</h2>
  <br>
  <p class="titlecontent mt-2">고관절이 아플때<br>어떤 운동을 하면 좋을까?</p>
  
  
  
  <button type="button" class="back btn-outline-danger btn-lg" onclick = 'location.href = "{% url 'curation:getQna' data.question_category.name data.id %}"'>시작하기</button>
  

{%endblock content%}

qna/qna/templates/curation/knee.html
{%extends 'curation/base.html'%}
{% load static%}

{%block content%}
<div class="col-lg-6 col-md-8 col-sm-10 col-12 mx-auto">
    <img src="{%static 'images/curation/knee.jpg'%}" alt="kneepain" class="img-fluid">
    </div>
  
  <p class="titlecontent mt-2">무릎이 아플때<br>어떤 운동을 하면 좋을까?</p>
  
  
  
  <button type="button" class="back btn-outline-danger btn-lg" onclick=onclick = 'location.href = "{% url 'curation:getQna' data.question_category.name data.id %}"'>시작하기</button>
  

{%endblock content%}

qna/qna/templates/curation/list.html
{%extends 'curation/base.html'%}
{% load static%}
{% load remainder %}


{%block content%}

<style>
    .grid-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        grid-template-rows: repeat(3, auto);
        grid-row-gap: 50px; /* Add the desired margin between rows */
        font-size: 25px;
    }
    .grid-container a{
        text-decoration: none;
        color: rgb(26, 26, 26);
    }
    .grid-container a:hover{color: #bb27ff!important;}

    .icon{
        text-align: right;
        font-size: 30px;
    }
    .icon a {
        margin-right: 30px; /* Adjust the value to set the desired margin */
        text-decoration: none;
        color: rgb(26, 26, 26);
    }
    .icon a:hover{color: #bb27ff!important;}
</style>

<div class="icon">
    <a href="#">QnA 수정</a>
    <a href="{%url 'curation:getQna' q_s.question_category.name.value q_s.id.value %}">QnA 테스트</a>
    <br><br>
</div>


<div class="grid-container">
    {% for q in question_data %}
        <div>
            <a href="{%url 'curation:edit' q.question.id %}">
            <strong>{{ q.question.question_text }}</strong>
            <br>
        
            {% for answer in q.answers %}
            {{ answer.answer_text }}
                <br>
            {% endfor %}
            </a>
        </div>
    {% endfor %}
</div>




{%endblock content%}

qna/qna/templates/curation/manage.html
{%extends 'curation/base.html'%}
{% load static%}
{% load remainder %}


{%block content%}
<style>
    .grid-container {
        display: grid;
        grid-template-columns: repeat(3, 1fr); /* Three columns */
        grid-gap: 10px; /* Gap between grid items */
    }
    .title{
        font-size: 32px;
    }
    a{
        text-decoration: none;
        color: black;
    }
    a:hover{color: #f78296!important;}
</style>

{% for item in data %}
    {% if user.id == item.author.id %}
        <div class="title">
        {% if forloop.counter|remainder:7 == 1 %}
            <!-- Index: {{ forloop.counter }} -->
            <a href="{%url 'curation:list' item.id %}">Q. {{ item.question_title }}</a>
            <br><br>
        {% endif %}
        </div>
    {%endif%}
{% endfor %}


{%endblock content%}

qna/qna/templates/curation/neck.html
{%extends 'curation/base.html'%}
{% load static%}

{%block content%}
<div class="col-lg-6 col-md-8 col-sm-10 col-12 mx-auto">
    <img src="{%static 'images/curation/neck.jpg'%}" alt="neckpain" class="img-fluid">
    </div>
  
  <p class="titlecontent mt-2">목이 아플때<br>어떤 운동을 하면 좋을까?</p>
  
  
  
 <button type="button" class="back btn-outline-danger btn-lg" onclick = 'location.href = "{% url 'curation:getQna' data.question_category.name data.id %}"' >시작하기</button>
  
{%endblock content%}